import type { Metadata } from "next";
import { Lilita_One} from "next/font/google";
import "./globals.css";

const brandFont = Lilita_One({subsets: ["latin"], weight: ["400"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="synthwave">
      <body
        className={brandFont.className}
      >
      
        {children}
        </body>
    </html>
  );
}
